### ISSUE TITLE
React to specific Kakera

### ISSUE THREAD

**Issue by zAzazyel** [vivinano/MudaeAutoBot#1]
Is there a way to react only to some types of Kakera, such as Yellow, Orange, Light ... Or will the bot react to everything that spawns? Sorry if this is already included in the settings, but I didn't find something like that

**Comment by vivinano** [comment]
I can probably add a way to get it to react to specfic ones. Currently how it works is that it check with there is "Kakera" that was added by mudae as reaction. So give me a bit and I will do some testing and close this issue when I figure out a solution

**Comment by zAzazyel** [comment]
Ok then. The outdated MudaeFarm from phosphene47 has a way to do it, but since it's all in C# idk if it would help you. There's no way to react to Light Kakera with MudaeFarm too because it's from a new mudae update.

**Comment by vivinano** [comment]
alright. Ive made changes to the code which should support Kak sniping. 

Ive added a array variable within settings_Mudae.json for kak_list currently it has all the kak possibilities all listed out. 
Just delete the lines of kakera variations you dont want to snipe. 

Don't worry about case Sensitivity as I factored for that user error so there wouldn't be any issues

I haven't tested the code so let me know if it still needs refining as its late and I wasn't able get a kakeraloot to appear in my rolls across servers

Do let me know If you need any other feature let me know and if I can close this issue

Thank you =)

**Comment by zAzazyel** [comment]
I tested it quickly and it is working with Light and ignoring the ones I removed. Later I will test with the others and bring other feedback. Thanks for the implementation!

**Comment by zAzazyel** [comment]
As I said, I am giving feedback after several tests. The new function is working very well with all the selected kakeras, I just have one last question. If I add the name of a custom or new emote, such as "candle" from new event, will the bot recognize and react as well? I think this is important in case new Mudae updates don't require a lot of code changes.

**Comment by vivinano** [comment]
How to code is set up as long as It is 
1. A Custom emoji
2. Name of the emoji is in the list

So how I orginally did the testing was with the "wright" and "wleft" emote provided by mudae so as long as its added into to list it will work 

there could be a issue if let say mudae adds like CandleC , CandleD 
and you have only "candle" in the list if i remember correctly since candle is in the list then it will react to both C and D also 

it the issue with "kakera" also since kakera is technically in All variations of kakeraP , kakeraL etc ... so if naming gets more intensive ill have to look into it further.

**Comment by zAzazyel** [comment]
I tested it once adding "candle" to the list and it didn't work. But as it is not something that appears frequently, I have not been able to test it many times. I will try a few more times and give u a feedback

**Comment by vivinano** [comment]
I see that candle is not a custom emoji in discord 

Is there a reason u need candle to be checked for ?

![image](https://user-images.githubusercontent.com/33008397/114285232-99374080-9a23-11eb-863a-f4f2bd8e7980.png)

**Comment by zAzazyel** [comment]
Not specifically. In the Mudae event now you need to react to the "candle" first, but I already completed that. I was testing for future events like this.

**Comment by vivinano** [comment]
Ive never participated in a mudae event so I have no knowledge of how those work. 
Is it always react to candle ? 

or is it like mudae react to this post ? If u have a screenshot of the thing i might be able to implement something but at the moment im unsure of the steps I would take to get to the goal of the event

**Comment by zAzazyel** [comment]
It works like a kakera reacts, u react to candle and collect it
![Capturar](https://user-images.githubusercontent.com/70450489/114285585-b0c7f680-9a2e-11eb-84a6-5b62f882e02d.PNG)

**Comment by vivinano** [comment]
alright so I made changes to the code 

instead of checking if its a custom emoji 
I made it check if the user is mudae bot

also keep in mind I also changed the Settings_mudae.json value from kak_list >>> emoji_list to avoid any confusion

and changed the code instead of checking for if it is "in" it has to be "equal to" to avoid it reacting to CandleC or CandleD in my example case

so check it out now and let me know as usual 

thank you =)

**Comment by vivinano** [comment]
oh wait there still an issue currently so the reason why I didnt account for non custom emojis is that candle or heart isnt recognized by its name like candle you actually have to use 🕯️ or ❤️ so this might take some thought

**Comment by vivinano** [comment]
Okay so i've again made changes to the code this time it works 
the kakera snipes are staying the same let me know if that still works 

but the event emoji's since they are not custom emoji's then they will have to be added within the mudaebot.py code 

sorry I couldnt make it simple as just adding the name of the emoji but "partialemojis" do not have **names** which **cant be added in json but directly in the code**

**Comment by zAzazyel** [comment]
I got it, I thought I was missing something in the settings, but it turned out to be more difficult than I thought. I will close and go to test now, thanks for all your attention.

**Comment by zAzazyel** [comment]
I'm reusing this place a lot ... So, kakera and snipe event are working, as well as snipe from the series list, but I still haven't managed to get Kakera's value snipe to work. Can you help me set this up?

**Comment by vivinano** [comment]
that is fine so the kakera value claim snipe Ive updated slightly from the original release to include getting a base value from only the like rank or the claim rank or both currently I have it set to be anything higher than 200 kak it will snipe

also depening on when you cloned the code I commented out the "snipe portion" for testing purposes so that could be a reason that its not sniping and just printing "Possible Claim" in the window

**Comment by vivinano** [comment]
Also the only other code that could possible stop the snipping is that it is checking for 
"React with any emoji to claim" within the embed to avoid reacting to users when they managing characters

**Comment by zAzazyel** [comment]
I did a few more tests and it worked on one channel, but not on others. Is there any necessary setting on channel as a prerequisite to sniping? The character even appears in the cmd logs, but does not snipe (i'm sure it's not togglesnipe bc it doesn't react and i already checked that it's on togglesnipe 0)

**Comment by vivinano** [comment]
do other channels have toggle like rank , toggle claim rank or togglekakera roll on ?

**Comment by zAzazyel** [comment]
The channel that is working has only togglekakera, the one that is not working has the three. The value even appeared in the logs, so it's identifying. I just don't know why it's not reacting.

**Comment by vivinano** [comment]
can you send a img of the thing that wasnt sniped ? cause the server I made it for has all 3 enabled and it hasnt given me any issues i even tested with a server that only has like and/or claim value

**Comment by vivinano** [comment]
i guess for good measure send me the img of the thing that was also sniped so I can compare between the 2 or figure out what is going wrong

**Comment by zAzazyel** [comment]
Can we talk in an email or something to make it easier?

**Comment by vivinano** [comment]
we can. I can join a discord server or do discord DM's if that is easier for you

**Comment by zAzazyel** [comment]
Sure, add me on discord "Tiredill#2986". i'll delete this msg soon for security

**Comment by vivinano** [comment]
Issues were with language other than english 

the code was checking for english only which cause issues with the code 

this was change to check for the "commands"  instead as they are universal across mudae
