### ISSUE TITLE
Mudae bot setup

### ISSUE THREAD

**Issue by koolyp0** [vivinano/MudaeAutoBot#123]
I doubt you'll see this but I'm completely new to this whole thing. Would you mind helping me set it up ?

**Comment by vivinano** [comment]
I see it I'm pretty active when it comes to supporting the repo for now 


As for set up I can assist in a few ways depending on what you need help with particularly

**Comment by koolyp0** [comment]
Im so sorry about this. I need help on everything. I have the python program downloaded but idk what to do next.

**Comment by vivinano** [comment]
After installing python you need to install discum module from their repo 

Afterwards you set up settings_mudae 

Get a channeldata instance 

And then run the python

**Comment by koolyp0** [comment]
![image](https://user-images.githubusercontent.com/76150321/140852798-e961467b-6a9e-44a0-9991-1ccca516d2d2.png)
Okay i installed discum, i did the settings. Im not sure how to get the channeldata thing

**Comment by vivinano** [comment]
$setting in the channel and it should automatically grab it

**Comment by koolyp0** [comment]
ummmmm, im so lost. does the program need to be running ? and if so this shows up 
![image](https://user-images.githubusercontent.com/76150321/140854791-a123118f-1987-4cb3-88d7-42a7b8ba2fa7.png)
ive never done any programming stuff so all this is new to me.

**Comment by vivinano** [comment]
You have to install it thru pip so all the files installed correctly and can run with python 

And no it’s fine we’ve all been there in terms of programming

**Comment by koolyp0** [comment]
Im so confused dude, do you mind working on a vid ? Im really dying to try it out. Im just not cut out for the programming stuff.

**Comment by vivinano** [comment]
The process of making a video would technically be pretty time consuming and this repo and all of its support is offered for free because I do it in my free time as it's pretty simple and easy. 

I usually send links and give tips on what to do and that would normally help people figure out how to set up the bot, but I can set out a time to personally help you with your bot set up. This is offered through my patreon though, because work is work. But I'll be able to walk you through set up one on one and teach you ways to optimize the bot for yourself.
