### ISSUE TITLE
Features support?

### ISSUE THREAD

**Issue by BellaDona007** [vivinano/MudaeAutoBot#219]
Hello, I would like to thank you for the very complete bot.
It is great to be used on a server that you play alone, even he easily not using the total number of rolls, usually leaving 1 leftover and not correctly identifying the claim time, not correctly using the `last_claim_min`. When it comes to playing on servers where you will play with other people these items and continues to roll even after having used claim, because it is not worth the risk of rolling and lose a wish, just to TRULY get a key, one thing that clearly denounces that it is selfbot is the bot roll EXACTLY always at the same time.

I would like to know if you have plans to or if someone else on the forum has implemented these features:
Start rolling at different times;
Pick up kakeras on servers with **$togglebuttons enabled**;
Stop rolling after picking up a character and automatically return to the reset claim time;

**Comment by vivinano** [comment]
Rolling at different times will not be implemented since all it will do it cause issues for me when ppl don't see that they are rolling 

Button support for kakera probably will come later when I have time as claiming wishes with button is implemented 

And as rolling and claiming are in different threads it would be some work for them to interact with each other that wouldn't introduce more bugs
