### ISSUE TITLE
Is custom emoji still supported

### ISSUE THREAD

**Issue by VSeaV** [vivinano/MudaeAutoBot#222]
Cant figure out how to do it, but read in another post that said it was deprecated. Any help?

**Comment by vivinano** [comment]
Custom emoji should still work but it was only really effective in one server if your not a nitro user so it’s like meh which is why I dropped support Sent from my iPhoneOn Dec 18, 2022, at 2:48 PM, VSeaV ***@***.***> wrote:﻿
Cant figure out how to do it, but read in another post that said it was deprecated. Any help?

**Comment by VSeaV** [comment]
> 

what line am i supposed to uncomment out?

**Comment by VSeaV** [comment]
> Custom emoji should still work but it was only really effective in one server if your not a nitro user so it’s like meh which is why I dropped support Sent from my iPhoneOn Dec 18, 2022, at 2:48 PM, VSeaV ***@***.***> wrote:﻿ Cant figure out how to do it, but read in another post that said it was deprecated. Any help? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

what line am i supposed to uncomment?

**Comment by snickermigger** [comment]
where did u change in the code? i'd like to use a custom emoji too
