### ISSUE TITLE
unable to get all the guilds

### ISSUE THREAD

**Issue by m-cf-b** [vivinano/MudaeAutoBot#261]
![image](https://github.com/vivinano/MudaeAutoBot/assets/87546884/5e28d3dd-0f5e-48a3-bdbd-1898fa074337)

**Comment by Nixeld** [comment]
I am having the same issue, how do i get a dump of all my guilds?

**Comment by RestumpY** [comment]
Same,

Reading from UserFile
It seems like you were unable to get all the guilds you are in please obtain your users settings
Please get a dump of all your guilds and put it in the userfolder
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000001E8AE9F62B0>>
Traceback (most recent call last):
  File "C:\Users\yanni\AppData\Local\Programs\Python\Python311\Lib\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\yanni\Desktop\MudaeAutoBot-main\MudaeAutoBot.py", line 808, in on_message
    for gid, guild in guilds.items():
                      ^^^^^^
UnboundLocalError: cannot access local variable 'guilds' where it is not associated with a value

**Comment by StuckInLimbo** [comment]
Same issue, fresh install. Using discum from git and no changes.

**Comment by amenslama30** [comment]
@vivinano help please

Reading from UserFile
It seems like you were unable to get all the guilds you are in please obtain your users settings
Please get a dump of all your guilds and put it in the userfolder
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x00000168C31DB6E0>>
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\amens\Desktop\MudaeAutoBot-main\MudaeAutoBot.py", line 808, in on_message
    for gid, guild in guilds.items():
                      ^^^^^^
UnboundLocalError: cannot access local variable 'guilds' where it is not associated with a value

**Comment by vivinano** [comment]
So I think with a change to discord there some issues grabbing account with several guilds a workaround currently is just manually grabbing the guild info you need for now as it doesn’t have to be all the guilds just the ones you need to work with Sent from my iPhoneOn Oct 27, 2023, at 5:51 PM, amenslama30 ***@***.***> wrote:﻿
@vivinano help please
Reading from UserFile
It seems like you were unable to get all the guilds you are in please obtain your users settings
Please get a dump of all your guilds and put it in the userfolder
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x00000168C31DB6E0>>
Traceback (most recent call last):
File "C:\Python312\Lib\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
func(resp)
File "C:\Users\amens\Desktop\MudaeAutoBot-main\MudaeAutoBot.py", line 808, in on_message
for gid, guild in guilds.items():
^^^^^^
UnboundLocalError: cannot access local variable 'guilds' where it is not associated with a value

**Comment by VineST** [comment]
@vivinano What should be the filename for the guild information? exguilds.txt appears to contain examples.

**Comment by vivinano** [comment]
Guilds.txt I think sorry have been pretty busy myself but you can use the example as like pseudo output all it needs it’s like guild number and stuff I think Sent from my iPhoneOn Nov 2, 2023, at 2:07 PM, VineST ***@***.***> wrote:﻿
@vivinano What should be the filename for the guild information? exguilds.txt appears to contain examples.

**Comment by VineST** [comment]
![image](https://github.com/vivinano/MudaeAutoBot/assets/6686964/76317f3b-211a-4c87-94ef-03f1256ac6d0)
Thanks; I filled out some info into a guilds.txt based on the example earlier with no dice. Tried changing it to uppercase but there's no effect. I also tried adding some user data into user.txt but that hasn't affected anything.

**Comment by Nixeld** [comment]
> Thanks; I filled out some info into a guilds.txt based on the example earlier with no dice. Tried changing it to uppercase but there's no effect. I also tried adding some user data into user.txt but that hasn't affected anything. e: Based on the source code it is looking for a `guild.txt`, not guilds.txt. I managed to read that guild.txt, but it is having trouble loading them into the requisite objects: ![image](https://user-images.githubusercontent.com/6686964/280381793-cb2e3955-816a-4439-8ddb-e355e47baa5e.png)

![image](https://github.com/vivinano/MudaeAutoBot/assets/18643932/364ef2a5-a227-42da-8079-1715677670e4)
![image](https://github.com/vivinano/MudaeAutoBot/assets/18643932/4a1f2559-3ae2-4e2d-97df-187db9972bf3)
Add in the json.loads()
This will convert it from a string to a dictionary

Replace all the following in user.txt and guild.txt
None to null
True to true
False to false

**Comment by VineST** [comment]
Thank you; I got it running and it actually somehow managed to roll once before failing due to using an outdated key in my settings file. I started the bot again with the same outdated key and it rolled once, claimed due to >500ka, and stopped again. 
Here's the errors with the outdated key:
![image](https://github.com/vivinano/MudaeAutoBot/assets/6686964/0b933ab7-a9e4-4176-a3b8-35b91c37dbf2)
They are about what one would expect; the curious part is how it managed to roll at all despite me being on a new session.

Thus, I tried loading my new auth key. But now, the bot does nothing after being started and does not log any text, only displaying this message after being force quit:
![image](https://github.com/vivinano/MudaeAutoBot/assets/6686964/25767b3f-e7ef-44c7-a0e2-a2bb6e94e89b)

**Comment by vivinano** [comment]
Ah okay so this is a string limitation thing alright that makes sense Sent from my iPhoneOn Nov 5, 2023, at 6:11 PM, VineST ***@***.***> wrote:﻿
Thank you; I got it running and it actually somehow managed to roll once before failing due to using an outdated key in my settings file. I started the bot again with the same outdated key and it rolled once, claimed due to >500ka, and stopped again.
Here's the errors with the outdated key:

They are about what one would expect; the curious part is how it managed to roll at all despite me being on a new session.
Thus, I tried loading my new auth key. But now, the bot does nothing after being started and does not log any text, only displaying this message after being force quit:

**Comment by Nixeld** [comment]
> Thank you! In addition to what you stated above, I also had to replace all single quotes in user.txt with double quotes and remove terminal commas in the guilds json.
Yeah I forgot to add that as well. Good that you were able to pick up on that problem. 

> I got it running and it actually somehow managed to roll once before failing due to using an outdated key in my settings file. I started the bot again with the same outdated key and it rolled once, claimed due to >500ka, and stopped again. Here's the errors with the outdated key: ![image](https://user-images.githubusercontent.com/6686964/280560684-65fb9c25-e5d1-48f6-8a56-bdf8daec3bf8.png) They are about what one would expect; the curious part is how it managed to roll at all despite me being on a new session.
> 
> Thus, I tried loading my new auth key. But now, the bot does nothing after being started and does not log any text, only displaying this message after being force quit: ![image](https://user-images.githubusercontent.com/6686964/280560625-25767b3f-e7ef-44c7-a0e2-a2bb6e94e89b.png)

Replace all `bot.gateway.session.user` with `user`.
This will stop the script from retrieving user information using the session gateway and retrieve from the user file instead.

**Comment by VineST** [comment]
Thanks for the tips on filtering more of those user sessions—do you have any advice as to why it's freezing during regular use now? The bot soft locks at `bot.gateway.run(auto_reconnect=True)` and can only be halted with CTRL+C.

**Comment by vivinano** [comment]
I can put these changes in when I have the time a lot of these things are discum things and the dev of that repo has kinda been busy himself to do updates Sent from my iPhoneOn Nov 8, 2023, at 2:31 AM, VineST ***@***.***> wrote:﻿
Thanks for the tips on filtering more of those user sessions—do you have any advice as to why it's freezing during regular use now? The bot soft locks at bot.gateway.run(auto_reconnect=True) and can only be halted with CTRL+C.

**Comment by Nixeld** [comment]
> Thanks for the tips on filtering more of those user sessions—do you have any advice as to why it's freezing during regular use now? The bot soft locks at `bot.gateway.run(auto_reconnect=True)` and can only be halted with CTRL+C. (screenshot in the previous post)

Not sure what's causing that, you can try changing console to True and see what comes out in the console.
![image](https://github.com/vivinano/MudaeAutoBot/assets/18643932/d2f7f0fa-8e81-412f-a1f2-f3a901a7b3bf)

**Comment by VineST** [comment]
> > Thanks for the tips on filtering more of those user sessions—do you have any advice as to why it's freezing during regular use now? The bot soft locks at `bot.gateway.run(auto_reconnect=True)` and can only be halted with CTRL+C. (screenshot in the previous post)
> 
> Not sure what's causing that, you can try changing console to True and see what comes out in the console. ![image](https://user-images.githubusercontent.com/18643932/281370747-d2f7f0fa-8e81-412f-a1f2-f3a901a7b3bf.png)

Thank you, this verbose logging is great—seems it's a different variety of authentication failure and I was using a malformed token!

I also had to comment this block out: 
![image](https://github.com/vivinano/MudaeAutoBot/assets/6686964/d9b8b304-01b5-47d9-b416-755a6478f9a5)
as part of the discum user API skipping.

The only issues I'm now experiencing are minor, such as the bot missing one roll (slash commands often fail once during a roll batch even as a human, so I assume the bot is experiencing the same thing), as well as the lack of kakera button sniping (a common issue reported multiple times that likely isn't slated to be fixed). I don't mind that much since I'm just using the bot to grind keys in a largely abandoned server.

**Comment by vivinano** [comment]
I think it’s something with the detection of kakera currently but that is weird Sent from my iPhoneOn Nov 8, 2023, at 12:56 PM, VineST ***@***.***> wrote:﻿


Thanks for the tips on filtering more of those user sessions—do you have any advice as to why it's freezing during regular use now? The bot soft locks at bot.gateway.run(auto_reconnect=True) and can only be halted with CTRL+C. (screenshot in the previous post)

Not sure what's causing that, you can try changing console to True and see what comes out in the console. 

Thank you, this verbose logging is great—seems it's a different variety of authentication failure and I was using a malformed token!
I also had to comment this block out:

as part of the discum user API skipping.
The only issues I'm now experiencing are minor, such as the bot missing one roll (slash commands often fail once during a roll batch even as a human, so I assume the bot is experiencing the same thing), as well as the lack of kakera button sniping (a common issue reported multiple times that likely isn't slated to be fixed). I don't mind that much since I'm just using the bot to grind keys in a largely abandoned server.

**Comment by VineST** [comment]
I'm slowly working to try debugging the button interface for kakera with my limited knowledge, since the wished rolls also use buttons and I haven't seen complaints about those not working (although I haven't actually tested it myself since my wishlist is all claimed characters for key gains).

**Comment by vivinano** [comment]
I apologize I personally have been so busy to actually bug fix and it’s only me working on the code base so I appreciate it Sent from my iPhoneOn Nov 8, 2023, at 5:33 PM, VineST ***@***.***> wrote:﻿
I'm slowly working to try debugging the button interface for kakera with my limited knowledge, since the wished rolls also use buttons and I haven't seen complaints about those not working (although I haven't actually tested it myself since my wishlist is all claimed characters for key gains).

**Comment by Nixeld** [comment]
> I'm slowly working to try debugging the button interface for kakera with my limited knowledge, since the wished rolls also use buttons and I haven't seen complaints about those not working (although I haven't actually tested it myself since my wishlist is all claimed characters for key gains).

https://github.com/vivinano/MudaeAutoBot/issues/246#issuecomment-1793827975
A quick fix for clicking on kakera button but without the check for kakera wall.

**Comment by vivinano** [comment]
feel free to put in the pull request so the changes can be applied universally as i dont have much time to make the required changes but i sure can push a button =D

**Comment by Ian99559999898** [comment]
can one of you guys help me im dying out here

**Comment by Nixeld** [comment]
> feel free to put in the pull request so the changes can be applied universally as i dont have much time to make the required changes but i sure can push a button =D

I don't mind opening a pull request but I have made a couple of changes to the code and most of them are just workarounds or quick fixes so it is kind of messy. Overall tried to keep most of the code unchanged while making sure that all the features are still working.

If you are fine with that then I will go ahead and open a pull request documenting the changes.
