### ISSUE TITLE
Bot eventually stops working

### ISSUE THREAD

**Issue by ghost** [vivinano/MudaeAutoBot#263]
After a certain amount of time, the bot just stops claiming, meaning it can't be run overnight. Is there a fix?

**Comment by vivinano** [comment]
Could you send a log file with the logging set to true of when it happens wants to see if there a reconnect issue to the discord gateway Sent from my iPhoneOn Sep 30, 2023, at 6:25 AM, magicalhobo2001 ***@***.***> wrote:﻿
After a certain amount of time, the bot just stops claiming, meaning it can't be run overnight. Is there a fix?

**Comment by magicalhobo2001** [comment]
Could you tell me how to do that? I'm sorry, I'm not very experienced with python and such.

> Could you send a log file with the logging set to true of when it happens wants to see if there a reconnect issue to the discord gateway Sent from my iPhoneOn Sep 30, 2023, at 6:25 AM, magicalhobo2001 ***@***.***> wrote:﻿ After a certain amount of time, the bot just stops claiming, meaning it can't be run overnight. Is there a fix? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by magicalhobo2001** [comment]
![image](https://github.com/vivinano/MudaeAutoBot/assets/143224357/ad4e6725-85b6-4fa4-a551-c73614413b51)

**Comment by magicalhobo2001** [comment]
> Could you send a log file with the logging set to true of when it happens wants to see if there a reconnect issue to the discord gateway 

Sorry to re-open this issue two months later, but for whatever reason the bot stops working once I set the file logging to true (cmd popping up for a split second and then disappearing). Console logging works, however.
![image](https://github.com/vivinano/MudaeAutoBot/assets/143224357/e7c45f77-28ef-4bc4-b056-64c7287ea264)
![image](https://github.com/vivinano/MudaeAutoBot/assets/143224357/6784381e-982f-4515-93b9-6edf568f4612)

**Comment by HentaiRyuu** [comment]
I also have this issue after reinstall python (and libs) and I have no idea how to fix, but I workaround it by set `bot.gateway.run(auto_reconnect=False)` and use other process to run bot when it close

someone on discum repo also mention this could help, but i tried and it not working for me
```
try:bot.gateway.subscribeToGuildEvents(wait=1)
except:pass
 ```

the problem is when it "**reconnect**" gateway wont send you message or anything except heartbeat (op11) but u could still use it normally like send message, slash (rolling), etc.
if you dont care about react char/kak and only grind keys, you can ignore this.

you could try replicate this problem by turn off/on your internet adapter
maybe also try reinstall python (and libs)

**Comment by vivinano** [comment]
@HentaiRyuu did it only start happening with new python install ?

**Comment by HentaiRyuu** [comment]
idk, but i assume it should relate to new install somehow
this issue used to happen to me year ago when i upgrade to py 3.11 then i roll back to 3.10 and it fix itself somehow
now i had to reinstall OS month ago then this issue is happen to me again, but this time it happen to any ver. of python i install so i had to workaround it by use other process to run bot when it close
