### ISSUE TITLE
Disable rolling if cannot claim?

### ISSUE THREAD

**Issue by cheroso1337** [vivinano/MudaeAutoBot#4]
is there any way to not roll if your account is on claiming cooldown?

**Comment by vivinano** [comment]
There is currently not implementation for that feature as since its multi-server I would have to think of a way to dynamically also grab the claim timer for each server being rolled and it get pretty complex and the current rolling implementation already breaks if someone else rolls during the bot rolls (Awaits a response is never gets and times out) . 

Its kind of for me an accepted risk type thing like even I'm not able to claim there still a chance maybe I will roll kakera or I will roll a key for a character I have. So rolling even tho I dont have a claim still has benefits

**Comment by vivinano** [comment]
Closing as rolling even without claim still has benefits of getting keys or potential kakera loots
