### ISSUE TITLE
Question: About bot reacting

### ISSUE THREAD

**Issue by Arkeo22** [vivinano/MudaeAutoBot#63]
If:
min_kak: 400
Series list: Genshin Impact
namelist: any 300k random char

When the bot is rolling, if i have a 300ka character in my namelist. Will he react? or only if is >400ka? happens same with series?

And if i have <400ka in my $wishlist, bot will take them?

Is there anyway to make the bot just claim your rolls, and make him dont snipe your friends?

I dont have that kequin emote, bot will be claiming anyway? (Changed it only if it doesnt too "use_emoji":"<:banana:>",)

Last question, do the bot claim the $daily and $dk?

**Comment by vivinano** [comment]
The bot checks each instance separately so 

It 1st does wish check , then name , the series and then finally kakera 

If it matches any one of them then it will attempt to go snipe only if it is not already sniped by the roller and within a valid claim window (having a claim available) if no claim is available then it will wait until next period to reactivate sniping mode 


And no it does not roll auto $DK or auto $daily 

As $dk I might make incorporate a check if it is available but currently there is no implementation as i feel like it might mess up and dk to early and waste someone gold IV perk 

And as for $daily I probably am not gonna implement this because i would have to start another thread for this alone and don’t feel like a whole thread dedicated to posting $daily once every 20h and then having to do a check if it is claimed

**Comment by vivinano** [comment]
Unsure if this will post but right now it use the heart emoji by default and if it finds a existing emoji it will add that one instead 

Json doesn’t support emojis like banana so if you have a standard emoji it has to be added within the code

**Comment by Arkeo22** [comment]
Thank you so much for  your answer!

Then you say that the bot check my wishlist? that is awesome.

For a last question: I see that bot try to take always the first $wa that match my config, but imagine this rolls with min_ka to 400:
Roll 200 random ka
Roll 47 random ka
Roll 87 random ka
Roll 430 random ka
Roll 700 ka character
Roll 1100 ka character

Bot willl instant take the 430ka character and 1100ka char will be lost. Is there any way to configurate the bot to: Do all his rolls first, and then pick?

**Comment by Arkeo22** [comment]
And happens same if talking bout names, does name order matter? If i have in my list: Zero Two, Albedo, Hatsune Miku and the bot rolls first Albedo and then Zero Two  (just a miracle happening xd), will he pick the fist he see (Albedo), or the first in my list(02)?

**Comment by Arkeo22** [comment]
And how can i config the bot to stop rolling when he have claimed, he continued rolling after claiming:

Our user rolled in 697172744344830094
Our user rolled in 697172744344830094
Our user rolled in 697172744344830094
2021-06-19 13:56:08,960:Seimei (SK) from Senran Kagura appeared attempting to snipe in 688439042395734057
Our user rolled in 697172744344830094
Our user rolled in 697172744344830094
Our user rolled in 697172744344830094
Our user rolled in 697172744344830094
True: Waifu rolling : 697172744344830094

**Comment by vivinano** [comment]
So bot rolls purposely even after because I wrote it in a way to claim for keys also rolls are handled by a different thread while rolls are handled on the main thread 
I might be to implement sniping when it finishes but it might run into timing issues as there a user with 50+ rolls and that might cause him to miss a character he rolled in half of his roll section 

As for the 1 sec to claim in instant snipe cases 

So currently there is a minor .5 sec wait to allow mudae to register that it is claimable and then the rest is based on computer processing speed and connection to discord as the bot sends commands to interact with discord api 

For order of snipes no it doesn’t matter it does it on a first come first serve basis so the 1st character to roll will get sniped whether is be from your own roll or someone else’s

**Comment by Arkeo22** [comment]
So there is no way to stop bot rolling if he cant claim? :(

**Comment by vivinano** [comment]
programmatically there could possible be a way to implement it by stopping the thread and starting it up again within the main thread but more people ask me they want to use all their rolls vs only rolling for themselves as like I stated before keys is the end game right

if you 10 key a character you can soulmate transfer them with you to any server and you get 50% discount on kakeraloots on them so optimally you would want to use all rolls whenever possible

**Comment by Arkeo22** [comment]
Is posible to make the bot snipe characters and kakera in various channels and only roll in one, or i need 2 of them, one normal and other one that dont roll?

**Comment by vivinano** [comment]
Yes there would be but it requires u to make edits to the code in terms of launching the rolling threads

**Comment by Arkeo22** [comment]
Thanks for all the answers! I close the post!
