### ISSUE TITLE
What should i edit to make the bot roll all his rolls and then claim.

### ISSUE THREAD

**Issue by Arkeo22** [vivinano/MudaeAutoBot#66]
Just happened this 20 min ago, bot rolled 2 characters: 1 is in bot list, and the other one is Wished, with 1 second dif:

![19b32b63e5c6197065dc344dcdeb82bf](https://user-images.githubusercontent.com/77751961/122713193-9ba8e880-d265-11eb-8bfb-c1dd6fb3e04d.png)

What should i change to config it, to wait until he finish rolling, and then claim by order: WishList>BotList (something like add some delay to the claim or idk)

**Comment by vivinano** [comment]
so how it coded currently is that each process is within its own thread 

basically each thread has a job to do but only does that one job. it is coded that way so they can work independently as if someone has their rolls to false then it has nothing to wait for 

which also brings into question roll # vary depending on each user a guy with 50 rolls or a user with 15 rolls have different wait times

you could set a static delay but this effects all claim times of the specific check instance you put it on  I.E
you roll only 1 character that worth 1560kak and u have it a static delay of 8 secs more then it will wait 8 extra secs b4 trying to claim and it might be claimed by someone else or expire 

main reason personally is that there is a msg cache but optimal snipe time calculations would be kinda not optimal

**Comment by vivinano** [comment]
you are free to make personal edits to the code to make it work the way you want to in terms of sniping im trying to keep it general enough for every1

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/123155259-e37e6a00-d435-11eb-83ba-aca26eef8e91.png)

so lines 442: 525 in the current version controls sniping logic if you want to modify that the fit your needs feel free to all your need to do is add an `and` statement the logic like I know 1 user does a series snipe but wants only ppl in that series that are higher than 400 kakera

but since this issue hasnt recieved a reply im gonna close it with this snippet of extra information
