### ISSUE TITLE
Does this selfbot only claim the waifu I roll myself?

### ISSUE THREAD

**Issue by akiya-zack** [vivinano/MudaeAutoBot#8]
I dont want claim other guys rolls

**Comment by vivinano** [comment]
what purpose would this serve ? 

just actually play ? without bot ? play on your own server ? have admin turn your server in to togglekakera2 or togglesnipe6 ?


I fail to see what benefit this "feature" will provide

**Comment by vivinano** [comment]
If you don't want to claim and only use the bot rolling features and not claim just fill the variables with junk that will never be "True" 
otherwise I haven't received a reply or a reason to implement a feature for claiming own characters as this defeats the purpose of having a automated sniping/rolling **selfbot** 

As a note I will also like to state that the features you requested seems like it will be better just to play** manually ** as using a **selfbot** you are taking a form of **Risk** for almost 0 benefits 

Will be closing as there hasn't been an answer
